


import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Nathan
 */
public class Copias extends javax.swing.JFrame {

    /**
     * Creates new form Copias
     */
    public Copias() {
        initComponents();
        
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/icon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ctxNumero = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ctxCopiaspbA4 = new javax.swing.JTextField();
        btnMais1 = new javax.swing.JButton();
        btnMenos1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnMenos2 = new javax.swing.JButton();
        ctxCopiaspbA3 = new javax.swing.JTextField();
        btnMais2 = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ctxCopiascA4 = new javax.swing.JTextField();
        btnMais3 = new javax.swing.JButton();
        btnMenos3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnMenos4 = new javax.swing.JButton();
        ctxCopiascA3 = new javax.swing.JTextField();
        btnMais4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        ctxArgolas = new javax.swing.JTextField();
        btnMais5 = new javax.swing.JButton();
        btnMenos5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnMenos6 = new javax.swing.JButton();
        ctxQuente = new javax.swing.JTextField();
        btnMais6 = new javax.swing.JButton();
        ctxTotal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnConcluir = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ctxNumero4 = new javax.swing.JTextField();
        ctxNome1 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Nº ou Nome de Registo:");

        ctxNumero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ctxNumero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ctxNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ctxNumeroKeyPressed(evt);
            }
        });

        btnPesquisar.setBackground(new java.awt.Color(51, 153, 255));
        btnPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisar.setText("Pesquisar...");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cópias Preto e Branco", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("A4");

        ctxCopiaspbA4.setEditable(false);
        ctxCopiaspbA4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ctxCopiaspbA4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ctxCopiaspbA4.setText("0");
        ctxCopiaspbA4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ctxCopiaspbA4.setEnabled(false);

        btnMais1.setBackground(new java.awt.Color(51, 153, 255));
        btnMais1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMais1.setForeground(new java.awt.Color(255, 255, 255));
        btnMais1.setText("+");
        btnMais1.setEnabled(false);
        btnMais1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMais1ActionPerformed(evt);
            }
        });

        btnMenos1.setBackground(new java.awt.Color(51, 153, 255));
        btnMenos1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMenos1.setForeground(new java.awt.Color(255, 255, 255));
        btnMenos1.setText("-");
        btnMenos1.setEnabled(false);
        btnMenos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenos1ActionPerformed(evt);
            }
        });

        jLabel3.setText("A3");

        btnMenos2.setBackground(new java.awt.Color(51, 153, 255));
        btnMenos2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMenos2.setForeground(new java.awt.Color(255, 255, 255));
        btnMenos2.setText("-");
        btnMenos2.setEnabled(false);
        btnMenos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenos2ActionPerformed(evt);
            }
        });

        ctxCopiaspbA3.setEditable(false);
        ctxCopiaspbA3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ctxCopiaspbA3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ctxCopiaspbA3.setText("0");
        ctxCopiaspbA3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ctxCopiaspbA3.setEnabled(false);

        btnMais2.setBackground(new java.awt.Color(51, 153, 255));
        btnMais2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMais2.setForeground(new java.awt.Color(255, 255, 255));
        btnMais2.setText("+");
        btnMais2.setEnabled(false);
        btnMais2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMais2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnMenos2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ctxCopiaspbA3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMais2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnMenos1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ctxCopiaspbA4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMais1)))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctxCopiaspbA4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMais1)
                    .addComponent(btnMenos1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctxCopiaspbA3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMais2)
                    .addComponent(btnMenos2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCancelar.setBackground(new java.awt.Color(51, 153, 255));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cópias Cores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("A4");

        ctxCopiascA4.setEditable(false);
        ctxCopiascA4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ctxCopiascA4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ctxCopiascA4.setText("0");
        ctxCopiascA4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ctxCopiascA4.setEnabled(false);

        btnMais3.setBackground(new java.awt.Color(51, 153, 255));
        btnMais3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMais3.setForeground(new java.awt.Color(255, 255, 255));
        btnMais3.setText("+");
        btnMais3.setEnabled(false);
        btnMais3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMais3ActionPerformed(evt);
            }
        });

        btnMenos3.setBackground(new java.awt.Color(51, 153, 255));
        btnMenos3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMenos3.setForeground(new java.awt.Color(255, 255, 255));
        btnMenos3.setText("-");
        btnMenos3.setEnabled(false);
        btnMenos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenos3ActionPerformed(evt);
            }
        });

        jLabel5.setText("A3");

        btnMenos4.setBackground(new java.awt.Color(51, 153, 255));
        btnMenos4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMenos4.setForeground(new java.awt.Color(255, 255, 255));
        btnMenos4.setText("-");
        btnMenos4.setEnabled(false);
        btnMenos4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenos4ActionPerformed(evt);
            }
        });

        ctxCopiascA3.setEditable(false);
        ctxCopiascA3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ctxCopiascA3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ctxCopiascA3.setText("0");
        ctxCopiascA3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ctxCopiascA3.setEnabled(false);

        btnMais4.setBackground(new java.awt.Color(51, 153, 255));
        btnMais4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMais4.setForeground(new java.awt.Color(255, 255, 255));
        btnMais4.setText("+");
        btnMais4.setEnabled(false);
        btnMais4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMais4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnMenos4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ctxCopiascA3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMais4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnMenos3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ctxCopiascA4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMais3)))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctxCopiascA4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMais3)
                    .addComponent(btnMenos3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctxCopiascA3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMais4)
                    .addComponent(btnMenos4))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Encadernações", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Argolas");

        ctxArgolas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ctxArgolas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ctxArgolas.setText("0");
        ctxArgolas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ctxArgolas.setEnabled(false);

        btnMais5.setBackground(new java.awt.Color(51, 153, 255));
        btnMais5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMais5.setForeground(new java.awt.Color(255, 255, 255));
        btnMais5.setText("+");
        btnMais5.setEnabled(false);
        btnMais5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMais5ActionPerformed(evt);
            }
        });

        btnMenos5.setBackground(new java.awt.Color(51, 153, 255));
        btnMenos5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMenos5.setForeground(new java.awt.Color(255, 255, 255));
        btnMenos5.setText("-");
        btnMenos5.setEnabled(false);
        btnMenos5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenos5ActionPerformed(evt);
            }
        });

        jLabel7.setText("Quente");

        btnMenos6.setBackground(new java.awt.Color(51, 153, 255));
        btnMenos6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMenos6.setForeground(new java.awt.Color(255, 255, 255));
        btnMenos6.setText("-");
        btnMenos6.setEnabled(false);
        btnMenos6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenos6ActionPerformed(evt);
            }
        });

        ctxQuente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ctxQuente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ctxQuente.setText("0");
        ctxQuente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ctxQuente.setEnabled(false);

        btnMais6.setBackground(new java.awt.Color(51, 153, 255));
        btnMais6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMais6.setForeground(new java.awt.Color(255, 255, 255));
        btnMais6.setText("+");
        btnMais6.setEnabled(false);
        btnMais6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMais6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnMenos6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ctxQuente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMais6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnMenos5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ctxArgolas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMais5)))
                .addGap(49, 49, 49))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctxArgolas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMais5)
                    .addComponent(btnMenos5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctxQuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMais6)
                    .addComponent(btnMenos6))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        ctxTotal.setEditable(false);
        ctxTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ctxTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Total:");

        btnConcluir.setBackground(new java.awt.Color(51, 153, 255));
        btnConcluir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnConcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnConcluir.setText("Concluir");
        btnConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcluirActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Número do Registro:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Nome do Registro:");

        ctxNumero4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ctxNumero4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ctxNumero4.setEnabled(false);

        ctxNome1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ctxNome1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ctxNome1.setEnabled(false);

        jPanel6.setBackground(new java.awt.Color(0, 0, 204));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Copy Count");

        lblMinimizar.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimizar.setText("-");
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseClicked(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_branco.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMinimizar)
                .addGap(31, 31, 31))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ctxNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctxNumero4, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnCancelar)
                                .addGap(622, 622, 622)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ctxTotal)
                            .addComponent(btnConcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(ctxNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnPesquisar))))
                .addGap(0, 59, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctxNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(ctxNumero4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ctxNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctxTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnConcluir))
                .addGap(17, 17, 17))
        );

        jPanel1.getAccessibleContext().setAccessibleName("Cópias Preto e Branco");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public static double saldo;
    public static int id;
    public static double total;
    DecimalFormat df = new DecimalFormat("0.00");
    public static double copiaspbA4=0.10;
    public static double copiaspbA3=0.20;
    public static double copiascA4=0.20;
    public static double copiascA3=0.40;
    public static double argolas=0.50;
    public static double quente=0.60;
    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        try {
            Pesquisar();
        } catch (Exception ex) {
            Logger.getLogger(Copias.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnMais1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMais1ActionPerformed
        int copias;
        copias= Integer.parseInt(ctxCopiaspbA4.getText())+1;
        ctxCopiaspbA4.setText(copias+"");       
        total = Integer.parseInt(ctxCopiaspbA4.getText())*copiaspbA4+Integer.parseInt(ctxCopiaspbA3.getText())*copiaspbA3
                +Integer.parseInt(ctxCopiascA4.getText())*copiascA4+Integer.parseInt(ctxCopiascA3.getText())*copiascA3
                +Integer.parseInt(ctxArgolas.getText())*argolas+Integer.parseInt(ctxQuente.getText())*quente;
        
        ctxTotal.setText(df.format(total)+"");
    }//GEN-LAST:event_btnMais1ActionPerformed

    private void btnMenos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenos1ActionPerformed
        int copias;
        if(ctxCopiaspbA4.getText().equals("0")){
            
        }else{
            copias= Integer.parseInt(ctxCopiaspbA4.getText())-1;
        ctxCopiaspbA4.setText(copias+"");       
        total = Integer.parseInt(ctxCopiaspbA4.getText())*copiaspbA4+Integer.parseInt(ctxCopiaspbA3.getText())*copiaspbA3
                +Integer.parseInt(ctxCopiascA4.getText())*copiascA4+Integer.parseInt(ctxCopiascA3.getText())*copiascA3
                +Integer.parseInt(ctxArgolas.getText())*argolas+Integer.parseInt(ctxQuente.getText())*quente;
        ctxTotal.setText(df.format(total)+"");
        }
    }//GEN-LAST:event_btnMenos1ActionPerformed

    private void btnMais2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMais2ActionPerformed
        int copias;
        copias= Integer.parseInt(ctxCopiaspbA3.getText())+1;
        ctxCopiaspbA3.setText(copias+"");       
        total = Integer.parseInt(ctxCopiaspbA4.getText())*copiaspbA4+Integer.parseInt(ctxCopiaspbA3.getText())*copiaspbA3
                +Integer.parseInt(ctxCopiascA4.getText())*copiascA4+Integer.parseInt(ctxCopiascA3.getText())*copiascA3
                +Integer.parseInt(ctxArgolas.getText())*argolas+Integer.parseInt(ctxQuente.getText())*quente;
        ctxTotal.setText(df.format(total)+"");
    }//GEN-LAST:event_btnMais2ActionPerformed

    private void btnMenos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenos2ActionPerformed
        int copias;
        if(ctxCopiaspbA3.getText().equals("0")){
            
        }else{
            copias= Integer.parseInt(ctxCopiaspbA3.getText())-1;
        ctxCopiaspbA3.setText(copias+"");       
        total = Integer.parseInt(ctxCopiaspbA4.getText())*copiaspbA4+Integer.parseInt(ctxCopiaspbA3.getText())*copiaspbA3
                +Integer.parseInt(ctxCopiascA4.getText())*copiascA4+Integer.parseInt(ctxCopiascA3.getText())*copiascA3
                +Integer.parseInt(ctxArgolas.getText())*argolas+Integer.parseInt(ctxQuente.getText())*quente;
        ctxTotal.setText(df.format(total)+"");
        }
        
    }//GEN-LAST:event_btnMenos2ActionPerformed

    private void btnMais3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMais3ActionPerformed
        int copias;
        copias= Integer.parseInt(ctxCopiascA4.getText())+1;
        ctxCopiascA4.setText(copias+"");       
        total = Integer.parseInt(ctxCopiaspbA4.getText())*copiaspbA4+Integer.parseInt(ctxCopiaspbA3.getText())*copiaspbA3
                +Integer.parseInt(ctxCopiascA4.getText())*copiascA4+Integer.parseInt(ctxCopiascA3.getText())*copiascA3
                +Integer.parseInt(ctxArgolas.getText())*argolas+Integer.parseInt(ctxQuente.getText())*quente;
        ctxTotal.setText(df.format(total)+"");
    }//GEN-LAST:event_btnMais3ActionPerformed

    private void btnMenos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenos3ActionPerformed
        int copias;
        if(ctxCopiascA4.getText().equals("0")){
            
        }else{
            copias= Integer.parseInt(ctxCopiascA4.getText())-1;
        ctxCopiascA4.setText(copias+"");       
        total = Integer.parseInt(ctxCopiaspbA4.getText())*copiaspbA4+Integer.parseInt(ctxCopiaspbA3.getText())*copiaspbA3
                +Integer.parseInt(ctxCopiascA4.getText())*copiascA4+Integer.parseInt(ctxCopiascA3.getText())*copiascA3
                +Integer.parseInt(ctxArgolas.getText())*argolas+Integer.parseInt(ctxQuente.getText())*quente;
        ctxTotal.setText(df.format(total)+"");
        }
        
    }//GEN-LAST:event_btnMenos3ActionPerformed

    private void btnMais4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMais4ActionPerformed
        int copias;
        copias= Integer.parseInt(ctxCopiascA3.getText())+1;
        ctxCopiascA3.setText(copias+"");       
        total = Integer.parseInt(ctxCopiaspbA4.getText())*copiaspbA4+Integer.parseInt(ctxCopiaspbA3.getText())*copiaspbA3
                +Integer.parseInt(ctxCopiascA4.getText())*copiascA4+Integer.parseInt(ctxCopiascA3.getText())*copiascA3
                +Integer.parseInt(ctxArgolas.getText())*argolas+Integer.parseInt(ctxQuente.getText())*quente;
        ctxTotal.setText(df.format(total)+"");
    }//GEN-LAST:event_btnMais4ActionPerformed

    private void btnMenos4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenos4ActionPerformed
        int copias;
        if(ctxCopiascA3.getText().equals("0")){
            
        }else{
            copias= Integer.parseInt(ctxCopiascA3.getText())-1;
        ctxCopiascA3.setText(copias+"");       
        total = Integer.parseInt(ctxCopiaspbA4.getText())*copiaspbA4+Integer.parseInt(ctxCopiaspbA3.getText())*copiaspbA3
                +Integer.parseInt(ctxCopiascA4.getText())*copiascA4+Integer.parseInt(ctxCopiascA3.getText())*copiascA3
                +Integer.parseInt(ctxArgolas.getText())*argolas+Integer.parseInt(ctxQuente.getText())*quente;
        ctxTotal.setText(df.format(total)+"");
        }
        
    }//GEN-LAST:event_btnMenos4ActionPerformed

    private void btnMais5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMais5ActionPerformed
        int copias;
        copias= Integer.parseInt(ctxArgolas.getText())+1;
        ctxArgolas.setText(copias+"");       
        total = Integer.parseInt(ctxCopiaspbA4.getText())*copiaspbA4+Integer.parseInt(ctxCopiaspbA3.getText())*copiaspbA3
                +Integer.parseInt(ctxCopiascA4.getText())*copiascA4+Integer.parseInt(ctxCopiascA3.getText())*copiascA3
                +Integer.parseInt(ctxArgolas.getText())*argolas+Integer.parseInt(ctxQuente.getText())*quente;
        ctxTotal.setText(df.format(total)+"");
    }//GEN-LAST:event_btnMais5ActionPerformed

    private void btnMenos5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenos5ActionPerformed
        int copias;
        if(ctxArgolas.getText().equals("0")){
            
        }else{
            copias= Integer.parseInt(ctxArgolas.getText())-1;
        ctxArgolas.setText(copias+"");       
        total = Integer.parseInt(ctxCopiaspbA4.getText())*copiaspbA4+Integer.parseInt(ctxCopiaspbA3.getText())*copiaspbA3
                +Integer.parseInt(ctxCopiascA4.getText())*copiascA4+Integer.parseInt(ctxCopiascA3.getText())*copiascA3
                +Integer.parseInt(ctxArgolas.getText())*argolas+Integer.parseInt(ctxQuente.getText())*quente;
        ctxTotal.setText(df.format(total)+"");
        }
        
    }//GEN-LAST:event_btnMenos5ActionPerformed

    private void btnMais6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMais6ActionPerformed
        int copias;
        copias= Integer.parseInt(ctxQuente.getText())+1;
        ctxQuente.setText(copias+"");       
        total = Integer.parseInt(ctxCopiaspbA4.getText())*copiaspbA4+Integer.parseInt(ctxCopiaspbA3.getText())*copiaspbA3
                +Integer.parseInt(ctxCopiascA4.getText())*copiascA4+Integer.parseInt(ctxCopiascA3.getText())*copiascA3
                +Integer.parseInt(ctxArgolas.getText())*argolas+Integer.parseInt(ctxQuente.getText())*quente;
        ctxTotal.setText(df.format(total)+"");
    }//GEN-LAST:event_btnMais6ActionPerformed

    private void btnMenos6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenos6ActionPerformed
        int copias;
        if(ctxQuente.getText().equals("0")){
            
        }else{
            copias= Integer.parseInt(ctxQuente.getText())-1;
        ctxQuente.setText(copias+"");       
        total = Integer.parseInt(ctxCopiaspbA4.getText())*copiaspbA4+Integer.parseInt(ctxCopiaspbA3.getText())*copiaspbA3
                +Integer.parseInt(ctxCopiascA4.getText())*copiascA4+Integer.parseInt(ctxCopiascA3.getText())*copiascA3
                +Integer.parseInt(ctxArgolas.getText())*argolas+Integer.parseInt(ctxQuente.getText())*quente;
        ctxTotal.setText(df.format(total)+"");
        }
        
    }//GEN-LAST:event_btnMenos6ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Tem a certeza que deseja cancelar a compra?", "Cancelar", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)==JOptionPane.YES_OPTION){
            this.dispose();
            MenuPrincipal m = new MenuPrincipal();
            m.setVisible(true);
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcluirActionPerformed
        
        if(total>saldo){
            JOptionPane.showMessageDialog(this,"Saldo insuficiente!", "Informação", JOptionPane.INFORMATION_MESSAGE);
        }else{
            saldo= saldo-total;
            try {
                UpdateSaldo();
            } catch (Exception ex) {
                Logger.getLogger(Copias.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                Adicionarobv();
            } catch (Exception ex) {
                Logger.getLogger(Copias.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(this,"Compra concluida com sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            MenuPrincipal m = new MenuPrincipal();
            m.setVisible(true);
        }
        
    }//GEN-LAST:event_btnConcluirActionPerformed

    private void ctxNumeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ctxNumeroKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            try {
            Pesquisar();
        } catch (Exception ex) {
            Logger.getLogger(Utilizadores.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_ctxNumeroKeyPressed

    private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_lblMinimizarMouseClicked
    
    public void Adicionarobv()throws Exception{
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        String observacao = dtf.format(now)+": Comprou ";
            if(ctxCopiaspbA4.getText().equals("0")){
                
            }else if(ctxCopiaspbA4.getText().equals("1")){
                observacao= observacao+ctxCopiaspbA4.getText()+" cópia a preto e branco A4, ";
            }else{
                observacao= observacao+ctxCopiaspbA4.getText()+" cópias a preto e branco A4, ";
            }
            if(ctxCopiaspbA3.getText().equals("0")){
                
            }else if(ctxCopiaspbA3.getText().equals("1")){
                observacao= observacao+ctxCopiaspbA3.getText()+" cópia a preto e branco A3, ";
            }else{
                observacao= observacao+ctxCopiaspbA3.getText()+" cópias a preto e branco A3, ";
            }
            if(ctxCopiascA4.getText().equals("0")){
                
            }else if(ctxCopiascA4.getText().equals("1")){
                observacao= observacao+ctxCopiascA4.getText()+" copia a cores A4, ";
            }else{
                observacao= observacao+ctxCopiascA4.getText()+" copias a cores A4, ";
            }
            if(ctxCopiascA3.getText().equals("0")){
                
            }else if(ctxCopiascA3.getText().equals("1")){
                observacao= observacao+ctxCopiascA3.getText()+" cópia a cores A3, ";
            }else{
                observacao= observacao+ctxCopiascA3.getText()+" cópias a cores A3, ";
            }
            if(ctxArgolas.getText().equals("0")){
                
            }else if(ctxArgolas.getText().equals("1")){
                observacao= observacao+ctxArgolas.getText()+" encadernação com argolas, ";
            }else{
                observacao= observacao+ctxArgolas.getText()+" encadernações com argolas, ";
            }
            if(ctxQuente.getText().equals("0")){
                
            }else if(ctxQuente.getText().equals("1")){
                observacao= observacao+ctxQuente.getText()+" encadernação quente, ";
            }else{
                observacao= observacao+ctxQuente.getText()+" encadernações quentes, ";
            }
            observacao= observacao+" dando um total de "+df.format(total)+"€.";
        Connection con = ConnectionFactory.getConnection().Conn();
        String query = "INSERT INTO observacoes (id_utilizador,observacao)"+
                                        "VALUES("+id+",'"+observacao+"')";
        PreparedStatement stmt = con.prepareStatement(query);
        stmt.execute();
        con.close();
    }
    
     public void Pesquisar() throws Exception{
        String numero,numero1=null,nome=null;
         id=0;
        numero = ctxNumero.getText();
        Connection con = ConnectionFactory.getConnection().Conn();
        String query = "SELECT * FROM utilizadores WHERE numero_utilizador='"+numero+"'";
        PreparedStatement stmt = con.prepareStatement(query);
        ResultSet resultado = stmt.executeQuery();
        while(resultado.next()){
            id = Integer.parseInt(resultado.getString("id_utilizador"));
            numero1 = resultado.getString("numero_utilizador");
            nome = resultado.getString("nome");
        }
        if(id==0){
            String query2 = "SELECT * FROM utilizadores WHERE nome='"+numero+"'";
            PreparedStatement stmt2 = con.prepareStatement(query2);
            ResultSet resultado2 = stmt2.executeQuery();
            while(resultado2.next()){
                id = Integer.parseInt(resultado2.getString("id_utilizador"));
                numero1 = resultado2.getString("numero_utilizador");
                nome = resultado2.getString("nome");
            }
            if(id==0){
                JOptionPane.showMessageDialog(this,"Número de utilizador inexistente!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            }else{
                String query3 = "SELECT * FROM saldo WHERE id_utilizador="+id+"";
                PreparedStatement stmt3 = con.prepareStatement(query3);
                ResultSet resultado3 = stmt3.executeQuery();
                while(resultado3.next()){
                    saldo = Float.parseFloat(resultado3.getString("saldo_utilizador"));
                }
                ctxNumero4.setText(numero1);
                ctxNome1.setText(nome);
                btnMais1.setEnabled(true);
                btnMenos1.setEnabled(true);
                btnMais2.setEnabled(true);
                btnMenos2.setEnabled(true);
                btnMais3.setEnabled(true);
                btnMenos3.setEnabled(true);
                btnMais4.setEnabled(true);
                btnMenos4.setEnabled(true);
                btnMais5.setEnabled(true);
                btnMenos5.setEnabled(true);
                btnMais6.setEnabled(true);
                btnMenos6.setEnabled(true);
                ctxCopiaspbA4.setEnabled(true);
                ctxCopiaspbA3.setEnabled(true);
                ctxCopiascA4.setEnabled(true);
                ctxCopiascA3.setEnabled(true);
                ctxArgolas.setEnabled(true);
                ctxQuente.setEnabled(true);
                }
            
        }else{
            String query1 = "SELECT * FROM saldo WHERE id_utilizador="+id+"";
            PreparedStatement stmt1 = con.prepareStatement(query1);
            ResultSet resultado1 = stmt1.executeQuery();
            while(resultado1.next()){
                saldo = Float.parseFloat(resultado1.getString("saldo_utilizador"));
            }
            ctxNumero4.setText(numero1);
            ctxNome1.setText(nome);
            btnMais1.setEnabled(true);
            btnMenos1.setEnabled(true);
            btnMais2.setEnabled(true);
            btnMenos2.setEnabled(true);
            btnMais3.setEnabled(true);
            btnMenos3.setEnabled(true);
            btnMais4.setEnabled(true);
            btnMenos4.setEnabled(true);
            btnMais5.setEnabled(true);
            btnMenos5.setEnabled(true);
            btnMais6.setEnabled(true);
            btnMenos6.setEnabled(true);
            ctxCopiaspbA4.setEnabled(true);
            ctxCopiaspbA3.setEnabled(true);
            ctxCopiascA4.setEnabled(true);
            ctxCopiascA3.setEnabled(true);
            ctxArgolas.setEnabled(true);
            ctxQuente.setEnabled(true);
        }
        con.close();
        
    }
     
     public void UpdateSaldo() throws Exception{
         Connection con = ConnectionFactory.getConnection().Conn();
        String query = "UPDATE saldo SET saldo_utilizador="+saldo+" WHERE id_utilizador="+id;
        PreparedStatement stmt = con.prepareStatement(query);
        stmt.execute();
        
        con.close();
     }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Copias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Copias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Copias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Copias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Copias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConcluir;
    private javax.swing.JButton btnMais1;
    private javax.swing.JButton btnMais2;
    private javax.swing.JButton btnMais3;
    private javax.swing.JButton btnMais4;
    private javax.swing.JButton btnMais5;
    private javax.swing.JButton btnMais6;
    private javax.swing.JButton btnMenos1;
    private javax.swing.JButton btnMenos2;
    private javax.swing.JButton btnMenos3;
    private javax.swing.JButton btnMenos4;
    private javax.swing.JButton btnMenos5;
    private javax.swing.JButton btnMenos6;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JTextField ctxArgolas;
    private javax.swing.JTextField ctxCopiascA3;
    private javax.swing.JTextField ctxCopiascA4;
    private javax.swing.JTextField ctxCopiaspbA3;
    private javax.swing.JTextField ctxCopiaspbA4;
    private javax.swing.JTextField ctxNome1;
    private javax.swing.JTextField ctxNumero;
    private javax.swing.JTextField ctxNumero4;
    private javax.swing.JTextField ctxQuente;
    private javax.swing.JTextField ctxTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblMinimizar;
    // End of variables declaration//GEN-END:variables
}
