 
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Nathan
 */
public class Utilizadores extends javax.swing.JFrame {

    /**
     * Creates new form Utilizadores
     */
    public Utilizadores() {
        initComponents();
        
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/icon.png")).getImage());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ctxNumero = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ctxNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ctxEmail = new javax.swing.JTextField();
        btnCriarRegistro = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ctxSaldo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ctxNumero1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ctxNome1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        ctxEmail1 = new javax.swing.JTextField();
        ctxNumero4 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        ctxNumero2 = new javax.swing.JTextField();
        btnPesquisar1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        ctxSaldoAtual = new javax.swing.JTextField();
        ctxAddSaldo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnAddSaldo = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        ctxNumero5 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        ctxNumero3 = new javax.swing.JTextField();
        btnPesquisar2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtObv = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 204));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Número do Registro:");

        ctxNumero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ctxNumero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Nome do Registro:");

        ctxNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ctxNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Email do Registro:");

        ctxEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ctxEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnCriarRegistro.setBackground(new java.awt.Color(51, 153, 255));
        btnCriarRegistro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCriarRegistro.setForeground(new java.awt.Color(255, 255, 255));
        btnCriarRegistro.setText("Criar Registro");
        btnCriarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarRegistroActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Saldo do Registro:");

        ctxSaldo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ctxSaldo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(28, 28, 28))
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ctxEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(ctxNome))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(ctxNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(ctxSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCriarRegistro))
                        .addContainerGap(397, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctxNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ctxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ctxEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ctxSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnCriarRegistro)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Criar Registo", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Nº ou Nome do Registro:");

        ctxNumero1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ctxNumero1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ctxNumero1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ctxNumero1KeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Nome do Registro:");

        ctxNome1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ctxNome1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ctxNome1.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Email do Registro:");

        btnPesquisar.setBackground(new java.awt.Color(51, 153, 255));
        btnPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisar.setText("Pesquisar...");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnAlterar.setBackground(new java.awt.Color(51, 153, 255));
        btnAlterar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterar.setText("Alterar Registro");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnApagar.setBackground(new java.awt.Color(51, 153, 255));
        btnApagar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnApagar.setForeground(new java.awt.Color(255, 255, 255));
        btnApagar.setText("Apagar Registro");
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });

        ctxEmail1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ctxEmail1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ctxEmail1.setEnabled(false);

        ctxNumero4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ctxNumero4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ctxNumero4.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Número do Registro:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ctxEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ctxNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnApagar)
                                .addGap(38, 38, 38)
                                .addComponent(btnAlterar))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(ctxNumero4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ctxNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPesquisar)
                .addGap(431, 431, 431))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ctxNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(ctxNumero4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ctxNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctxEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterar)
                    .addComponent(btnApagar))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Alterar/Apagar Registo", jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Nº ou Nome do Registro:");

        ctxNumero2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ctxNumero2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ctxNumero2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ctxNumero2KeyPressed(evt);
            }
        });

        btnPesquisar1.setBackground(new java.awt.Color(51, 153, 255));
        btnPesquisar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPesquisar1.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisar1.setText("Pesquisar...");
        btnPesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisar1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Saldo Atual:");

        ctxSaldoAtual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ctxSaldoAtual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ctxSaldoAtual.setEnabled(false);

        ctxAddSaldo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ctxAddSaldo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ctxAddSaldo.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Adicionar Saldo:");

        btnAddSaldo.setBackground(new java.awt.Color(51, 153, 255));
        btnAddSaldo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAddSaldo.setForeground(new java.awt.Color(255, 255, 255));
        btnAddSaldo.setText("Adicionar Saldo");
        btnAddSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSaldoActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Número do Registro:");

        ctxNumero5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ctxNumero5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ctxNumero5.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAddSaldo)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                            .addComponent(ctxAddSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ctxSaldoAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ctxNumero2, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                                    .addComponent(ctxNumero5))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPesquisar1)
                .addContainerGap(239, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ctxNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctxNumero5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctxSaldoAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ctxAddSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnAddSaldo)
                .addGap(108, 108, 108))
        );

        jTabbedPane1.addTab("Carregar Saldo", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Número do Registro:");

        ctxNumero3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ctxNumero3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ctxNumero3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ctxNumero3KeyPressed(evt);
            }
        });

        btnPesquisar2.setBackground(new java.awt.Color(51, 153, 255));
        btnPesquisar2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPesquisar2.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisar2.setText("Pesquisar...");
        btnPesquisar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisar2ActionPerformed(evt);
            }
        });

        txtObv.setEditable(false);
        txtObv.setColumns(20);
        txtObv.setRows(5);
        txtObv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(txtObv);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ctxNumero3, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPesquisar2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctxNumero3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Histórico do Registo", jPanel5);

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Voltar para o Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(0, 0, 204));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Copy Count");

        lblMinimizar.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimizar.setText("-");
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseClicked(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_branco.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 681, Short.MAX_VALUE)
                .addComponent(lblMinimizar)
                .addGap(31, 31, 31))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(11, 11, 11)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 899, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        MenuPrincipal m = new MenuPrincipal();
        m.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCriarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarRegistroActionPerformed
        try {
            Criar();
        } catch (Exception ex) {
            Logger.getLogger(Utilizadores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCriarRegistroActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        try {
            Pesquisar();
        } catch (Exception ex) {
            Logger.getLogger(Utilizadores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnPesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisar1ActionPerformed
        try {
            Pesquisar1();
        } catch (Exception ex) {
            Logger.getLogger(Utilizadores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPesquisar1ActionPerformed

    private void btnAddSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSaldoActionPerformed
        try {
            AdicionarSaldo();
        } catch (Exception ex) {
            Logger.getLogger(Utilizadores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddSaldoActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        try {
            Apagar();
        } catch (Exception ex) {
            Logger.getLogger(Utilizadores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnApagarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        try {
            Alterar();
        } catch (Exception ex) {
            Logger.getLogger(Utilizadores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnPesquisar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisar2ActionPerformed
        try {
            Pesquisar2();
        } catch (Exception ex) {
            Logger.getLogger(Utilizadores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPesquisar2ActionPerformed

    private void ctxNumero1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ctxNumero1KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            try {
            Pesquisar();
        } catch (Exception ex) {
            Logger.getLogger(Utilizadores.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_ctxNumero1KeyPressed

    private void ctxNumero2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ctxNumero2KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            try {
            Pesquisar1();
        } catch (Exception ex) {
            Logger.getLogger(Utilizadores.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_ctxNumero2KeyPressed

    private void ctxNumero3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ctxNumero3KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            try {
            Pesquisar2();
        } catch (Exception ex) {
            Logger.getLogger(Utilizadores.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_ctxNumero3KeyPressed

    private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_lblMinimizarMouseClicked
    
    public static float saldoatual;
    public static int id;
    
    public void Criar() throws Exception{
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        String numero, nome, email;
        float saldo;
        id = 0;
        if(ctxNumero.getText().equals("")||ctxNumero.getText().length()!=9){
            JOptionPane.showMessageDialog(this,"Número de Registo inválido ou inferior a 9 caracteres"
                    + "!", "Informação", JOptionPane.INFORMATION_MESSAGE);
        }else{
            numero = ctxNumero.getText();
            if(ctxNome.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Nome de Registo inválido!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            }else{
                nome = ctxNome.getText();
                if(ctxEmail.getText().equals("")){
                    JOptionPane.showMessageDialog(this,"Email de Registo inválido!", "Informação", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    email = ctxEmail.getText();
                    if(ctxSaldo.getText().equals("")){
                        JOptionPane.showMessageDialog(this,"Saldo inválido!", "Informação", JOptionPane.INFORMATION_MESSAGE);
                    }else{
                        saldo = Float.parseFloat(ctxSaldo.getText());
                        Connection con = ConnectionFactory.getConnection().Conn();
                        String query = "INSERT INTO utilizadores (numero_utilizador,nome,email)"+
                                        "VALUES('"+numero+"','"+nome+"','"+email+"')";
                        PreparedStatement stmt = con.prepareStatement(query);
        
                        stmt.execute();
                        String query1 = "SELECT * FROM utilizadores WHERE numero_utilizador='"+numero+"'";
                        PreparedStatement stmt1 = con.prepareStatement(query1);
                        ResultSet resultado = stmt1.executeQuery();
                        while(resultado.next()){
                            id = Integer.parseInt(resultado.getString("id_utilizador"));
                        }
                        String query2 = "INSERT INTO saldo (id_utilizador,saldo_utilizador)"+
                                        "VALUES("+id+",'"+saldo+"')";
                        PreparedStatement stmt2 = con.prepareStatement(query2);
                        stmt2.execute();
                        String observacao= dtf.format(now)+" Registo criado!";
                        String query23 = "INSERT INTO observacoes (id_utilizador,observacao)"+
                                        "VALUES("+id+",'"+observacao+"')";
                        PreparedStatement stmt23 = con.prepareStatement(query23);
                        stmt23.execute();
                        con.close();
                        JOptionPane.showMessageDialog(this,"Resgisto criado com sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);
                        ctxNumero.setText("");
                        ctxNome.setText("");
                        ctxEmail.setText("");
                        ctxSaldo.setText("");
                        
                    }
                    
                }
                
            }               
            
        }
        
    }
    
    public void Pesquisar() throws Exception{
        String numero,nome=null,email=null,numero1 = null;
        numero = ctxNumero1.getText();
        id=0;
        Connection con = ConnectionFactory.getConnection().Conn();
        String query = "SELECT * FROM utilizadores WHERE numero_utilizador='"+numero+"'";
        PreparedStatement stmt = con.prepareStatement(query);
        ResultSet resultado = stmt.executeQuery();
        while(resultado.next()){
            id = Integer.parseInt(resultado.getString("id_utilizador"));
            numero1 = resultado.getString("numero_utilizador");
            nome = resultado.getString("nome");
            email = resultado.getString("email");
        }
        if(nome==null || email==null){
            String query1 = "SELECT * FROM utilizadores WHERE nome='"+numero+"'";
            PreparedStatement stmt1 = con.prepareStatement(query1);
            ResultSet resultado1 = stmt1.executeQuery();
            while(resultado1.next()){
                id = Integer.parseInt(resultado1.getString("id_utilizador"));
                numero1 = resultado1.getString("numero_utilizador");
                nome = resultado1.getString("nome");
                email = resultado1.getString("email");
            }
            if(nome==null || email==null){
                JOptionPane.showMessageDialog(this,"Número de utilizador inexistente!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            }else{
                ctxNumero4.setText(numero1);
                ctxNome1.setText(nome);
                ctxEmail1.setText(email);
                ctxNumero4.setEnabled(true);
                ctxNome1.setEnabled(true);
                ctxEmail1.setEnabled(true);
                ctxNumero1.setText("");
            }
            
        }else{
            ctxNumero4.setText(numero1);
            ctxNome1.setText(nome);
            ctxEmail1.setText(email);
            ctxNumero4.setEnabled(true);
            ctxNome1.setEnabled(true);
            ctxEmail1.setEnabled(true);
            ctxNumero1.setText("");
        }
        con.close();
        
    }
    
    public void Pesquisar1() throws Exception{
        String numero,numero1=null;
        id=0;
        saldoatual=-1;
        numero = ctxNumero2.getText();
        Connection con = ConnectionFactory.getConnection().Conn();
        String query = "SELECT * FROM utilizadores WHERE numero_utilizador='"+numero+"'";
        PreparedStatement stmt = con.prepareStatement(query);
        ResultSet resultado = stmt.executeQuery();
        while(resultado.next()){
            id = Integer.parseInt(resultado.getString("id_utilizador"));
            numero1 = resultado.getString("numero_utilizador");
        }
        String query1 = "SELECT saldo_utilizador FROM saldo WHERE id_utilizador="+id+"";
        PreparedStatement stmt1 = con.prepareStatement(query1);
        ResultSet resultado1 = stmt1.executeQuery();
        while(resultado1.next()){
            saldoatual = Float.parseFloat(resultado1.getString("saldo_utilizador"));
        }
        if(saldoatual==-1){
            String query2 = "SELECT * FROM utilizadores WHERE nome='"+numero+"'";
            PreparedStatement stmt2 = con.prepareStatement(query2);
            ResultSet resultado2 = stmt2.executeQuery();
            while(resultado2.next()){
                id = Integer.parseInt(resultado2.getString("id_utilizador"));
                numero1 = resultado2.getString("numero_utilizador");
            }
            String query12 = "SELECT saldo_utilizador FROM saldo WHERE id_utilizador="+id+"";
            PreparedStatement stmt12 = con.prepareStatement(query12);
            ResultSet resultado12 = stmt12.executeQuery();
            while(resultado12.next()){
                saldoatual = Float.parseFloat(resultado12.getString("saldo_utilizador"));
            }
            if(saldoatual==-1){
                JOptionPane.showMessageDialog(this,"Número de utilizador inexistente!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            }else{
                ctxNumero5.setText(numero1);
                ctxSaldoAtual.setText(saldoatual+"€");
                ctxAddSaldo.setEnabled(true);
                ctxNumero2.setText("");
            }
                
        }else{
            ctxNumero5.setText(numero1);
            ctxSaldoAtual.setText(saldoatual+"€");
            ctxAddSaldo.setEnabled(true);
            ctxNumero2.setText("");
        }
        con.close();
        
    }
    
    public void Pesquisar2() throws Exception{
        String numero;
        id=0;
        numero = ctxNumero3.getText();
        Connection con = ConnectionFactory.getConnection().Conn();
        String query = "SELECT * FROM utilizadores WHERE numero_utilizador='"+numero+"'";
        PreparedStatement stmt = con.prepareStatement(query);
        ResultSet resultado = stmt.executeQuery();
        while(resultado.next()){
            id = Integer.parseInt(resultado.getString("id_utilizador"));
        }
        String query1 = "SELECT observacao FROM observacoes WHERE id_utilizador="+id+"";
        PreparedStatement stmt1 = con.prepareStatement(query1);
        ResultSet resultado1 = stmt1.executeQuery();
        while(resultado1.next()){
            txtObv.setText(txtObv.getText()+resultado1.getNString("observacao")+"\n");
        }
        if(id==0){
            String query2 = "SELECT * FROM utilizadores WHERE nome='"+numero+"'";
            PreparedStatement stmt2 = con.prepareStatement(query2);
            ResultSet resultado2 = stmt2.executeQuery();
            while(resultado2.next()){
                id = Integer.parseInt(resultado2.getString("id_utilizador"));
            }
            String query12 = "SELECT observacao FROM observacoes WHERE id_utilizador="+id+"";
            PreparedStatement stmt12 = con.prepareStatement(query12);
            ResultSet resultado12 = stmt12.executeQuery();
            while(resultado12.next()){
                txtObv.setText(txtObv.getText()+resultado12.getNString("observacao")+"\n");
            }
            if(id==0){
                JOptionPane.showMessageDialog(this,"Número de utilizador inexistente!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            }           
        }else{
        }
        con.close();
    }
    
    public void AdicionarSaldo() throws Exception{
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        double saldoadcn=0,totalSaldo=0;
        saldoadcn= Float.parseFloat(ctxAddSaldo.getText());
        totalSaldo = saldoatual+saldoadcn;
        String observacao = dtf.format(now)+": Carregou o seu saldo com "+saldoadcn+"€.";
        Connection con = ConnectionFactory.getConnection().Conn();
        String query = "UPDATE saldo SET saldo_utilizador="+totalSaldo+" WHERE id_utilizador="+id;
        PreparedStatement stmt = con.prepareStatement(query);
        stmt.execute();
        
        String query1 = "INSERT INTO observacoes (id_utilizador,observacao)"+
                                        "VALUES("+id+",'"+observacao+"')";
        PreparedStatement stmt1 = con.prepareStatement(query1);
        stmt1.execute();
        con.close();
        JOptionPane.showMessageDialog(this,"Saldo adicionado com sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);
        ctxAddSaldo.setText("");
        ctxSaldoAtual.setText("");
        ctxAddSaldo.setEnabled(false);
    }
    
    public void Apagar() throws Exception{
        if(JOptionPane.showConfirmDialog(this, "Tem a certeza que deseja eliminar este Registo?", "Apagar Registo", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)==JOptionPane.YES_OPTION){
            Connection con = ConnectionFactory.getConnection().Conn();
            String query = "DELETE FROM utilizadores WHERE id_utilizador="+id;
            PreparedStatement stmt = con.prepareStatement(query);
            stmt.execute();
        
            con.close();
            ctxNumero4.setText("");
            ctxNome1.setText("");
            ctxEmail1.setText("");
            ctxNumero4.setEnabled(false);
            ctxNome1.setEnabled(false);
            ctxEmail1.setEnabled(false);
            JOptionPane.showMessageDialog(this,"Registo apagado com sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    public void Alterar() throws Exception{
        String numero=null, nome=null, email=null;
        numero= ctxNumero4.getText();
        nome= ctxNome1.getText();
        email= ctxEmail1.getText();
        Connection con = ConnectionFactory.getConnection().Conn();
        String query = "UPDATE utilizadores SET numero_utilizador='"+numero+"', nome='"+nome+"', email='"+email+"' WHERE id_utilizador="+id;
        PreparedStatement stmt = con.prepareStatement(query);
        stmt.execute();
        
        con.close();
        ctxNumero4.setText("");
        ctxNome1.setText("");
        ctxEmail1.setText("");
        ctxNumero4.setEnabled(false);
        ctxNome1.setEnabled(false);
        ctxEmail1.setEnabled(false);
        JOptionPane.showMessageDialog(this,"Registo alterado com sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Utilizadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Utilizadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Utilizadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Utilizadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Utilizadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSaldo;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnCriarRegistro;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnPesquisar1;
    private javax.swing.JButton btnPesquisar2;
    private javax.swing.JTextField ctxAddSaldo;
    private javax.swing.JTextField ctxEmail;
    private javax.swing.JTextField ctxEmail1;
    private javax.swing.JTextField ctxNome;
    private javax.swing.JTextField ctxNome1;
    private javax.swing.JTextField ctxNumero;
    private javax.swing.JTextField ctxNumero1;
    private javax.swing.JTextField ctxNumero2;
    private javax.swing.JTextField ctxNumero3;
    private javax.swing.JTextField ctxNumero4;
    private javax.swing.JTextField ctxNumero5;
    private javax.swing.JTextField ctxSaldo;
    private javax.swing.JTextField ctxSaldoAtual;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblMinimizar;
    private javax.swing.JTextArea txtObv;
    // End of variables declaration//GEN-END:variables
}
